name: Generate Plugin Index

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: List files
        run: ls

      - name: Install Index Generator
        run: |
          Invoke-WebRequest -Uri https://github.com/ClassIsland/ClassIsland.PluginIndexGenerator/releases/download/1.0.2.1/ClassIsland.PluginIndexGenerator.zip -OutFile ClassIsland.PluginIndexGenerator.zip
          Expand-Archive -Path ClassIsland.PluginIndexGenerator.zip -DestinationPath .
      
      - name: Generate Plugin Index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir out/source/
          ./ClassIsland.PluginIndexGenerator.exe index out/source/index.json -b base.json -t $env:GITHUB_TOKEN
          7z a "./out/index.zip" ./out/source/* -r -mx=9
          
      - name: Generate MD5
        run: |
          pwsh -ep Bypass -c .\tools\generate-md5.ps1 ./out

      - name: Upload Artifacts to Actions
        uses: actions/upload-artifact@v3
        with:
          name: index-artifacts
          path: ./out/*
